#!/usr/bin/env ruby

require 'digest/md5'
require 'fileutils'

input = ARGF.read
file = "/tmp/#{Digest::MD5.hexdigest input}.emacs-pager"

File.open(file, 'w') do |f|
  f.write(input)
end

puts 'reading into emacs...'

`emacsclient #{file}`

FileUtils.rm(file)
